[program:gutshoes-horizon]
process_name=%(program_name)s
command=php /var/www/gutshoes/apps/backend/artisan horizon
directory=/var/www/gutshoes/apps/backend
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/gutshoes-horizon.log
stopwaitsecs=3600

[program:gutshoes-scheduler]
command=php /var/www/gutshoes/apps/backend/artisan schedule:work
directory=/var/www/gutshoes/apps/backend
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/supervisor/gutshoes-scheduler.log
