<?php

use App\Http\Controllers\Api\V1\AddressController;
use App\Http\Controllers\Api\V1\AdminBrandController;
use App\Http\Controllers\Api\V1\AdminCategoryController;
use App\Http\Controllers\Api\V1\AdminFulfillmentController;
use App\Http\Controllers\Api\V1\AdminOperationsController;
use App\Http\Controllers\Api\V1\AdminProductController;
use App\Http\Controllers\Api\V1\AdminSizeController;
use App\Http\Controllers\Api\V1\CancellationRefundController;
use App\Http\Controllers\Api\V1\CartController;
use App\Http\Controllers\Api\V1\CatalogController;
use App\Http\Controllers\Api\V1\CheckoutQuoteController;
use App\Http\Controllers\Api\V1\CustomerOrderController;
use App\Http\Controllers\Api\V1\GuestOrderController;
use App\Http\Controllers\Api\V1\OrderController;
use App\Http\Controllers\Api\V1\PaymentController;
use App\Http\Controllers\Api\V1\ProfileController;
use App\Http\Controllers\Api\V1\ReadinessController;
use App\Http\Controllers\Api\V1\RegionController;
use App\Http\Controllers\Api\V1\SessionController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->middleware('throttle:api')->group(function (): void {
    Route::get('/health/ready', ReadinessController::class)->middleware('throttle:health');
    Route::get('/health', fn () => response()->json(['data' => ['status' => 'ok', 'service' => 'gutshoes-api', 'timestamp' => now()->utc()->toIso8601String()]]))->name('api.v1.health');
    Route::get('/regions/provinces', [RegionController::class, 'provinces']);
    Route::get('/regions/regencies', [RegionController::class, 'regencies']);
    Route::get('/regions/districts', [RegionController::class, 'districts']);
    Route::get('/regions/villages', [RegionController::class, 'villages']);
    Route::get('/products', [CatalogController::class, 'index']);
    Route::get('/products/{slug}', [CatalogController::class, 'show']);
    Route::post('/payments/midtrans/webhook', [PaymentController::class, 'webhook'])->middleware('throttle:webhooks');
    Route::post('/orders/track', [CustomerOrderController::class, 'track'])->middleware('throttle:tracking');

    Route::middleware('web')->group(function (): void {
        Route::get('/cart', [CartController::class, 'show']);
        Route::post('/cart/items', [CartController::class, 'storeItem']);
        Route::patch('/cart/items/{item}', [CartController::class, 'updateItem']);
        Route::delete('/cart/items/{item}', [CartController::class, 'deleteItem']);
        Route::post('/checkout/quote', CheckoutQuoteController::class)->middleware('throttle:checkout');
        Route::post('/orders', [OrderController::class, 'store'])->middleware('throttle:checkout');
        Route::post('/orders/{orderNumber}/payment', [PaymentController::class, 'store'])->middleware('throttle:checkout');
        Route::get('/guest/orders/{orderNumber}', [GuestOrderController::class, 'show'])->middleware('throttle:tracking');
        Route::post('/guest/orders/{orderNumber}/payment', [GuestOrderController::class, 'payment'])->middleware('throttle:checkout');
        Route::post('/orders/{orderNumber}/cancel', [CancellationRefundController::class, 'cancel'])->middleware('throttle:checkout');
        Route::post('/admin/auth/login', [SessionController::class, 'adminLogin'])->middleware('throttle:auth');
        Route::middleware('auth:sanctum')->group(function (): void {
            Route::post('/cart/claim', [CartController::class, 'claim']);
            Route::get('/auth/me', [SessionController::class, 'me']);
            Route::post('/auth/logout', [SessionController::class, 'logout']);
            Route::get('/profile', [ProfileController::class, 'show']);
            Route::put('/profile', [ProfileController::class, 'update']);
            Route::apiResource('addresses', AddressController::class);
            Route::get('/orders', [CustomerOrderController::class, 'index']);
            Route::get('/orders/{orderNumber}', [CustomerOrderController::class, 'show']);
            Route::prefix('admin')->middleware(['admin', 'audit.admin'])->group(function (): void {
                Route::get('/dashboard', [AdminOperationsController::class, 'dashboard']);
                Route::get('/orders', [AdminOperationsController::class, 'orders']);
                Route::get('/orders/{order}', [AdminOperationsController::class, 'order']);
                Route::get('/payments', [AdminOperationsController::class, 'payments']);
                Route::get('/shipments', [AdminOperationsController::class, 'shipments']);
                Route::get('/cancellations', [AdminOperationsController::class, 'cancellations']);
                Route::get('/refunds', [AdminOperationsController::class, 'refunds']);
                Route::get('/customers', [AdminOperationsController::class, 'customers']);
                Route::get('/audit-logs', [AdminOperationsController::class, 'auditLogs']);
                Route::get('/promotions', [AdminOperationsController::class, 'promotions']);
                Route::post('/promotions', [AdminOperationsController::class, 'savePromotion']);
                Route::put('/promotions/{promotion}', [AdminOperationsController::class, 'savePromotion']);
                Route::delete('/promotions/{promotion}', [AdminOperationsController::class, 'deletePromotion']);
                Route::get('/vouchers', [AdminOperationsController::class, 'vouchers']);
                Route::post('/vouchers', [AdminOperationsController::class, 'saveVoucher']);
                Route::put('/vouchers/{voucher}', [AdminOperationsController::class, 'saveVoucher']);
                Route::delete('/vouchers/{voucher}', [AdminOperationsController::class, 'deleteVoucher']);
                Route::get('/inventories', [AdminOperationsController::class, 'inventories']);
                Route::get('/inventory-options', [AdminOperationsController::class, 'inventoryOptions']);
                Route::post('/inventories', [AdminOperationsController::class, 'createInventory']);
                Route::get('/inventories/{inventory}/movements', [AdminOperationsController::class, 'inventoryMovements']);
                Route::patch('/inventories/{inventory}/adjust', [AdminOperationsController::class, 'adjustInventory']);
                Route::delete('/inventories/{inventory}', [AdminOperationsController::class, 'deleteInventory']);
                Route::get('/configurations', [AdminOperationsController::class, 'configurations']);
                Route::put('/configurations/{key}', [AdminOperationsController::class, 'updateConfiguration']);
                Route::patch('/orders/{order}/fulfillment', [AdminFulfillmentController::class, 'update']);
                Route::post('/refunds/{refund}/process', [CancellationRefundController::class, 'refund']);
                Route::apiResource('brands', AdminBrandController::class);
                Route::apiResource('categories', AdminCategoryController::class);
                Route::apiResource('sizes', AdminSizeController::class)->except('show');
                Route::apiResource('products', AdminProductController::class);
                Route::post('/products/{product}/publish', [AdminProductController::class, 'publish']);
                Route::post('/products/{product}/images', [AdminProductController::class, 'uploadImage']);
                Route::delete('/products/{product}/images/{image}', [AdminProductController::class, 'deleteImage']);
            });
        });
    });
});
